language: java

jdk:
  - oraclejdk8

# whitelist
branches:
  only:
    - master
    - Development
    - Garrison-Branch

after_success:
  - mvn clean test jacoco:report coveralls:report
